# Generated by Django 3.2.3 on 2021-06-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characterCard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='age',
        ),
    ]
