# Generated by Django 3.2.3 on 2021-06-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characterCard', '0002_remove_character_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
    ]
