# Generated by Django 3.2.3 on 2021-07-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterCard', '0005_character_luck'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='item',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
