# Generated by Django 3.2.3 on 2021-07-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterCard', '0006_character_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('nerv', 'Zdenerwowanie'), ('horror', 'Przerażenie'), ('fatigue', 'Zmęczenie'), ('injury', 'Zranienie'), ('weaknes', 'Wycieńczenie')], max_length=50, null=True),
        ),
    ]
