# Generated by Django 3.2.3 on 2021-07-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterCard', '0007_character_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='motivation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='pride',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='problem',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='song',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='support',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('Normalny', 'Normal'), ('Zdenerwowanie', 'Nervousness'), ('Przerażenie', 'Horror'), ('Zmęczenie', 'Fatigue'), ('Zranienie', 'Injury'), ('Wycieńczenie', 'Weakness')], max_length=50, null=True),
        ),
    ]
