# Generated by Django 3.2.3 on 2021-07-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterCard', '0009_auto_20210722_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='sneaking',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True),
        ),
    ]
