# Generated by Django 3.2.3 on 2021-07-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterCard', '0011_auto_20210722_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
