# Generated by Django 3.2.3 on 2021-07-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterCard', '0013_auto_20210724_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='status',
            new_name='status1',
        ),
        migrations.AddField(
            model_name='character',
            name='status2',
            field=models.CharField(choices=[('Normalny', 'Normal'), ('Zdenerwowanie', 'Nervousness'), ('Przerażenie', 'Horror'), ('Zmęczenie', 'Fatigue'), ('Zranienie', 'Injury'), ('Wycieńczenie', 'Weakness')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='status3',
            field=models.CharField(choices=[('Normalny', 'Normal'), ('Zdenerwowanie', 'Nervousness'), ('Przerażenie', 'Horror'), ('Zmęczenie', 'Fatigue'), ('Zranienie', 'Injury'), ('Wycieńczenie', 'Weakness')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='status4',
            field=models.CharField(choices=[('Normalny', 'Normal'), ('Zdenerwowanie', 'Nervousness'), ('Przerażenie', 'Horror'), ('Zmęczenie', 'Fatigue'), ('Zranienie', 'Injury'), ('Wycieńczenie', 'Weakness')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='status5',
            field=models.CharField(choices=[('Normalny', 'Normal'), ('Zdenerwowanie', 'Nervousness'), ('Przerażenie', 'Horror'), ('Zmęczenie', 'Fatigue'), ('Zranienie', 'Injury'), ('Wycieńczenie', 'Weakness')], max_length=50, null=True),
        ),
    ]
