# Generated by Django 3.2.3 on 2021-07-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterCard', '0015_auto_20210724_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
            ],
        ),
    ]
