# Generated by Django 3.2.3 on 2021-07-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterCard', '0016_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='titleSpan',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
