# Generated by Django 3.2.3 on 2021-07-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterCard', '0017_home_titlespan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='body',
            field=models.TextField(max_length=255),
        ),
    ]
