# Generated by Django 3.2.3 on 2021-07-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characterCard', '0018_alter_home_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='tile',
            new_name='title',
        ),
    ]
