# Generated by Django 3.2.3 on 2021-07-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterCard', '0019_rename_tile_home_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='body',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='headquarters',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='heart',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='mind',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='technique',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
