# Generated by Django 3.2.3 on 2021-07-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterCard', '0020_auto_20210725_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='realtion1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='realtion2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='realtion3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='realtion4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='realtionBn1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='realtionBn2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='realtionBn3',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
