# Generated by Django 3.2.3 on 2021-07-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterCard', '0021_auto_20210728_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='exp',
            field=models.CharField(choices=[('1/10', '1'), ('2/10', '2'), ('3/10', '3'), ('4/10', '4'), ('5/10', '5'), ('6/10', '6'), ('7/10', '7'), ('8/10', '8'), ('9/10', '9'), ('10/10', '10')], max_length=50, null=True),
        ),
    ]
