# Generated by Django 3.2.3 on 2021-08-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterCard', '0023_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('alt', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
